-- 코드를 작성해주세요
SELECT ID,
    CASE
        WHEN A.CLASS = 1 THEN 'CRITICAL'
        WHEN A.CLASS = 2 THEN 'HIGH'
        WHEN A.CLASS = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, 
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS CLASS
    FROM ECOLI_DATA
) AS A
ORDER BY ID;