-- 코드를 작성해주세요
SELECT i2.ITEM_ID, i2.ITEM_NAME, i2.RARITY
FROM ITEM_INFO i JOIN ITEM_TREE t JOIN ITEM_INFO i2
ON i.ITEM_ID = t.PARENT_ITEM_ID AND i2.ITEM_ID = t.ITEM_ID
WHERE i.RARITY = 'RARE'
ORDER BY i2.ITEM_ID DESC;