-- 코드를 작성해주세요
SELECT mx.YEAR AS YEAR, (mx.MAX_SIZE - ed.SIZE_OF_COLONY) AS YEAR_DEV, ed.ID
FROM ECOLI_DATA ed
JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) mx
ON YEAR(DIFFERENTIATION_DATE) = mx.YEAR
ORDER BY YEAR, YEAR_DEV;